import = [
    "~/.config/alacritty/tokyo-night-alacritty-theme/tokyo-night.toml"
]

[scrolling]
    history = 5000
    multiplier = 3
[font]
    normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
    bold = {family = "FiraCode Nerd Font Mono", style = "Bold"}
[selection]
    save_to_clipboard = true
[cursor]
    unfocused_hollow = true
[env]
    TERM = "xterm-256color"
